return {
  icons = {
    diagnostics = {
      Error = "󰻕 ",
      Warn = "󰈻 ",
      Hint = "󰌵 ",
      Info = "󱗆 ",
    },
    git = {
      added = "󰐖 ",
      modified = "󰏬 ",
      removed = "󰍵 ",
    },
    kinds = {
      Array = "󰅪 ",
      Boolean = "󰨙 ",
      Class = "󰙅 ",
      Color = "󰏘 ",
      Constant = "󰐀 ",
      Constructor = "󰖵 ",
      Copilot = "󰊤 ",
      Enum = "󰸼 ",
      EnumMember = "󰸿 ",
      Event = "󰈸 ",
      Field = "󰆧 ",
      File = "󰈔 ",
      Folder = "󰉋 ",
      Function = "󰊕 ",
      Interface = "󱘖 ",
      Key = "󰌆 ",
      Keyword = "󰌋 ",
      Method = "󰊕 ",
      Module = "󰏗 ",
      Namespace = "󰏖 ",
      Null = "󰱥 ",
      Number = "󰲠 ",
      Object = "󰠱 ",
      Operator = "󰿉 ",
      Package = "󰏓 ",
      Property = "󰆦 ",
      Reference = "󰑨 ",
      Snippet = "󰼹 ",
      String = "󰥛 ",
      Struct = "󰭆 ",
      Text = "󰙩 ",
      TypeParameter = "󰗢 ",
      Unit = "󱍓 ",
      Value = "󰆬 ",
      Variable = "󰮯 ",
    },
  },
  devicons = {
    filename = {
      [".eslintrc.js"] = {
        icon = "󰱺",
        color = "#4b32c3",
        cterm_color = "56",
        name = "EslintrcJs",
      },
      [".eslintrc.json"] = {
        icon = "󰱺",
        color = "#4b32c3",
        cterm_color = "56",
        name = "EslintrcJson",
      },
      [".eslintrc.cjs"] = {
        icon = "󰱺",
        color = "#4b32c3",
        cterm_color = "56",
        name = "EslintrcCjs",
      },
      [".eslintrc.yaml"] = {
        icon = "󰱺",
        color = "#4b32c3",
        cterm_color = "56",
        name = "EslintrcYaml",
      },
      [".eslintrc.yml"] = {
        icon = "󰱺",
        color = "#4b32c3",
        cterm_color = "56",
        name = "EslintrcYml",
      },
      [".gitignore"] = {
        icon = "󰊢",
        color = "#41535b",
        cterm_color = "239",
        name = "GitIgnore",
      },
      [".nvmrc"] = {
        icon = "󰋙",
        color = "#68a063",
        cterm_color = "28",
        name = "Nvmrc",
      },
      ["package.json"] = {
        icon = "󰋘",
        color = "#e8274b",
        name = "PackageJson",
      },
      ["tailwind.config.js"] = {
        icon = "󱏿",
        color = "#38bdf8",
        name = "TailwindConfigJs",
      },
      ["webpack"] = {
        icon = "󰜫",
        color = "#519aba",
        cterm_color = "74",
        name = "Webpack",
      },
    },
    extension = {
      ["cjs"] = {
        icon = "󰌞",
        color = "#cbcb41",
        cterm_color = "185",
        name = "Cjs",
      },
      ["mjs"] = {
        icon = "󰌞",
        color = "#cbcb41",
        cterm_color = "185",
        name = "Mjs",
      },
      ["js"] = {
        icon = "󰌞",
        color = "#cbcb41",
        cterm_color = "185",
        name = "Js",
      },
      ["test.js"] = {
        icon = "󰳪",
        color = "#cbcb41",
        cterm_color = "185",
        name = "TestJs",
      },
      ["spec.js"] = {
        icon = "󰳪",
        color = "#cbcb41",
        cterm_color = "185",
        name = "SpecJs",
      },
      ["test.jsx"] = {
        icon = "󰳪",
        color = "#20c2e3",
        cterm_color = "45",
        name = "JavaScriptReactTest",
      },
      ["spec.jsx"] = {
        icon = "󰳪",
        color = "#20c2e3",
        cterm_color = "45",
        name = "JavaScriptReactSpec",
      },
      ["log"] = {
        icon = "󰯂",
        color = "#ffffff",
        cterm_color = "231",
        name = "Log",
      },
      ["md"] = {
        icon = "",
        color = "#ffffff",
        cterm_color = "231",
        name = "Md",
      },
      ["mdx"] = {
        icon = "",
        color = "#519aba",
        cterm_color = "74",
        name = "Mdx",
      },
      ["pdf"] = {
        icon = "󰈦",
        color = "#b30b00",
        cterm_color = "124",
        name = "Pdf",
      },
      ["prisma"] = {
        icon = "",
        color = "#ffffff",
        cterm_color = "231",
        name = "Prisma",
      },
      ["sol"] = {
        icon = "󱓻",
        color = "#519aba",
        cterm_color = "74",
        name = "Solidity",
      },
      ["svg"] = {
        icon = "󰜡",
        color = "#FFB13B",
        cterm_color = "214",
        name = "Svg",
      },
      ["ts"] = {
        icon = "󰛦",
        color = "#519aba",
        cterm_color = "74",
        name = "Ts",
      },
      ["test.ts"] = {
        icon = "󰳪",
        color = "#519aba",
        cterm_color = "74",
        name = "TestTs",
      },
      ["spec.ts"] = {
        icon = "󰳪",
        color = "#519aba",
        cterm_color = "74",
        name = "SpecTs",
      },
      ["test.tsx"] = {
        icon = "󰳪",
        color = "#1354bf",
        cterm_color = "26",
        name = "TypeScriptReactTest",
      },
      ["spec.tsx"] = {
        icon = "󰳪",
        color = "#1354bf",
        cterm_color = "26",
        name = "TypeScriptReactSpec",
      },
      ["txt"] = {
        icon = "󰎞",
        color = "#89e051",
        cterm_color = "113",
        name = "Txt",
      },
      ["xml"] = {
        icon = "󰗀",
        color = "#e37933",
        cterm_color = "166",
        name = "Xml",
      },
      ["yaml"] = {
        icon = "󰒓",
        color = "#6d8086",
        cterm_color = "66",
        name = "Yaml",
      },
      ["yml"] = {
        icon = "󰒓",
        color = "#6d8086",
        cterm_color = "66",
        name = "Yml",
      },
    },
  },
}
