return {
  icons = {
    diagnostics = {
      Error = "ﮏ ",
      Warn = " ",
      Hint = " ",
      Info = " ",
    },
    git = {
      added = "烙",
      modified = " ",
      removed = "ﮖ ",
    },
    kinds = {
      Array = " ",
      Boolean = " ",
      Class = " ",
      Color = " ",
      Constant = " ",
      Constructor = "華",
      Copilot = " ",
      Enum = " ",
      EnumMember = " ",
      Event = " ",
      Field = " ",
      File = " ",
      Folder = " ",
      Function = " ",
      Interface = "禍",
      Key = " ",
      Keyword = " ",
      Method = " ",
      Module = " ",
      Namespace = " ",
      Null = "ﳠ ",
      Number = " ",
      Object = "ﰪ ",
      Operator = "󰿉 ",
      Package = " ",
      Property = " ",
      Reference = "ﱈ ",
      Snippet = "廉",
      String = "﮼ ",
      Struct = "襁",
      Text = "ﭨ ",
      TypeParameter = " ",
      Unit = " ",
      Value = " ",
      Variable = " ",
    },
  },
}
